blank_issues_enabled: true
contact_links:
  - name: Question or Discussion
    url: https://github.com/schrmm/schrmm.github.io/discussions
    about: For questions or general discussions, please use GitHub Discussions
